"""Small, framework-neutral contracts for CrowdTensor training sessions."""

from .contracts import (
    ArtifactRef,
    CheckpointLineage,
    CheckpointRef,
    ContractError,
    ContributionReceipt,
    ReceiptOutcome,
    TrainingMode,
    TrainingProject,
    WorkUnit,
    stable_hash,
    validate_receipt_binding,
)
from .controller import (
    SessionController,
    SessionControllerError,
    inspect_session_controller,
)
from .data_packs import DataPack, DataPackError
from .execution import (
    ProviderSnapshot,
    ResourceAvailability,
    StableShardedLaunchSpec,
    TrainingExecutionPlan,
)
from .workspace import (
    WorkspaceError,
    export_workspace,
    init_project,
    init_project_contract,
    inspect_workspace,
    join_workspace,
    load_project,
    load_recorded_plan,
    pause_workspace,
    record_plan,
    resume_workspace,
    run_workspace,
)

__all__ = [
    "ArtifactRef",
    "CheckpointLineage",
    "CheckpointRef",
    "ContractError",
    "ContributionReceipt",
    "DataPack",
    "DataPackError",
    "ReceiptOutcome",
    "ProviderSnapshot",
    "ResourceAvailability",
    "SessionController",
    "SessionControllerError",
    "StableShardedLaunchSpec",
    "TrainingMode",
    "TrainingExecutionPlan",
    "TrainingProject",
    "WorkUnit",
    "WorkspaceError",
    "export_workspace",
    "init_project",
    "init_project_contract",
    "inspect_workspace",
    "inspect_session_controller",
    "join_workspace",
    "load_project",
    "load_recorded_plan",
    "pause_workspace",
    "record_plan",
    "resume_workspace",
    "run_workspace",
    "stable_hash",
    "validate_receipt_binding",
]
